name: pingster
description: A chat application similar to WhatsApp or Telegram.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  go_router: ^6.0.1
  flutter_spinkit: ^5.2.1
  animate_do: ^3.3.4
  flutter_svg: ^2.0.10+1
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  flutter_sound: ^9.6.0
  encrypt: ^5.0.3
  firebase_storage: ^11.6.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
